# .github/workflows/**main.yml**
name: Django-app workflow

on: [push]

jobs:
  tests:
    # «Раннер» — создание изолированного окружения с последней версией Ubuntu 
    runs-on: ubuntu-latest

    steps:
    # Запуск actions checkout — готового скрипта 
    # для клонирования репозитория
    - uses: actions/checkout@v2
    - name: Set up Python
      # Запуск actions setup-python — готового скрипта 
      # для развёртывания окружения Python
      uses: actions/setup-python@v2
      with:
        # Выбор версии Python
        python-version: 3.7

    - name: Install dependencies
      run: | 
        # обновление pip
        python -m pip install --upgrade pip 
        # установка flake8 и его плагинов
        pip install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort
        # установка зависимостей
        pip install -r requirements.txt 

    - name: Test with flake8 and django tests
      run: |
        # запуск проверки проекта по flake8
        python -m flake8
  build_and_push_to_docker_hub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Check out the repo
        # Проверка доступности репозитория Docker Hub для workflow
        uses: actions/checkout@v2 
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1 
      - name: Login to Docker 
        uses: docker/login-action@v1 
        with:
           username: anton60874022
           password: ZvfJdsq3+
      - name: Push to Docker Hub 
        uses: docker/build-push-action@v2 
        with:
          push: true
          tags: anton60874022/456:latest
  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push_to_docker_hub
    steps:
      - name: executing remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        with:
          host: 130.193.39.134
          username: anton60874022
          key: b3BlbnNzaC1rZXktdjEAAAAACmFlczI1Ni1jdHIAAAAGYmNyeXB0AAAAGAAAABAmXqAsXv
                6c+ZWIeuPNyxzmAAAAEAAAAAEAAAGXAAAAB3NzaC1yc2EAAAADAQABAAABgQCns3YQcRg8
                1CPRiRptAHQeK5S2SkcZadSc+YEnJnX5bTs/eRWQUX4l5GpmKhxLoLTJtz18nAffaH7YXe
                GeR7udLqOXTXeqIzGoRtYi+wZOtNthxozXJKsz4rvKBMFoDwD1XdzKQgT4nZWkoy7Oae3i
                Pqkoe1TLKcqstz4ln58myGBM0l706VsFXnrHhqLbthQSuZ1OfkxuWMXjH/+R7EV4WIr+Qb
                I8/lmZJB71UECo+cJywKGAKptwi4yLw0OiA1sMyd0V/nj9U+kSLU/tRZvHyI9fmx267EF8
                QMzlb8Qr1S6OLEetuQ6QYIdwowpFETYmAYxSR4KH3m3Bire4ueXYObYsWFC5KV6fs1MvRL
                hEf83qifrmJUsHORT7VxqZKHS81CXKOsXV2k/Vr2NDCCtgwrVatoUYDaYjM5mp4u9tWIUP
                KP0w2yQhbd38GyGtKX5yCk7EdCl4AYg6AUgSdcIZXaNzmliCOi8noQu/KIOZtNCb5ivJaS
                SDvqKGXzr4UKkAAAWgZwdEr7IBgwnyhDwVnwTeYIRJJ4LBwYi8V9XQxYdbz2I3bpb1fF3H
                O7s/q2W5b7kk1fBF+YtnG9CIWzAF9QxIZGm/QWa3i0k8YJyc94boXAbVQmMwF1raenqWNc
                XGmhdM4K1a05X7NuZnG4xhgduxDHZ5CvyPnlikqPoKVRA5zSCMX6jkWM/nPMVrID5eOWLc
                YrRraEc/tyRe63b7e8KptNCs9gNwZZ6hqjMG/VQTCzHt5sjl0McEEbsL2lotVfkboUMOzN
                vm3YCtgv9WL7JtlAGb7uykCAdl80euCzIsUVywW6yk423YBweg65NlsSWqFFGao43rD4D6
                IWbIYIDy/++ShtEim7ZqRuAJFKCBcSW7xxHSNm8pezcALU1N8xzrdsvEJtZFY7nzbco5NR
                f02RSs/PySoyOK6X3M8azhMrzyBfGfgwF02qEQeFr2rZJSdl+xTW+0sDOQReF/hn4mrHBE
                Q2mZNuUotBqN9fz8QXZ8E/2+Xm5XdA6LldiRlaAl8Oz+CwsST0lAGHnOf4AiMXuajGYiBk
                V9E6ql4A2+V2H/T8viEr+cnwcZds0ULYtvqWhevZXHaZH5+yoCyio7Wfqu41e0s6DNyyGS
                AVd2LXiAyk90ionzivSSYvJ5eNDOm8V3lOw0QCAWvH8pSDhSk9WNrsyGlaIfvm6Xwhkqqs
                x8NhOVaUfjHCusdx5rWqPewNP4JwOosRN6AKdG5qCVomw3uz/zNScvyE1V9Lrtr6RdQ7zG
                HFB4IHrGsj9mJ0PBqAtTBo2rhHTk4znY63m3XQ/VdyN0iz42KJeOPjxGCpmCxSmu+FLOjW
                0kZcRfVxotUf1xKYdOVIWERNibzh3eZnGHL0G/4dHxLoR3khr1jnXqx1LZO4YcXRoYpAcr
                Glu7XQcb6AJfdKfbQVXNlm0ZfXyluK0EdRiIGhQ4AEFRC7M5Q6FByOOjmgw2UgXoG77tw+
                GuUMITuvabFpel55D8BbJNlqt6aAxJAEXvYZGMY2HsXGr1sMxRJbWJ/8kLUcDs1RVyAHu6
                /TgVxlQ3U7yx36WjcfjujJmZPpTnnOU0TH26wf+9gHvuQJpPsSSkuAXC5VzSTeZ20o+Kyd
                FFo5IvDXq9Uuhr+bpnuEzYJjBoZFwlR+Db3tyvQKQ//Ot9xXGELaI9HL4xYD4LIvqjQ991
                OSdyQrIlOg0EDtFuTxWnsnSP7ULcWeaw4H7J9tbE8lik9gCewHO1LNfwGomStSAvRDgDv0
                l9ToXN5MGgruBFZhX+tQhAf1exlRc/NfDZOFZX3PqHVhsYBp7uWLoiM4MvOWOY2d1PLzFX
                9QipDCtK9bkRRltNsobsxd5rgzCj1QwsJGuR8wzzZy3J317VrrHHFrPdJVQ3zzcm/DJICX
                5SmnsLzYiCHLUXEkrRq0b26lSQF7YPjw/8ODxzHbdMeBbRr2UitezzjEhrWU5NLk2LxLYe
                8q3O41BRBgJbF4um5Pi4bhHRH6mFfNZKg68TjujRnXi1ckxxK6IT0jL/HTOGGkoHX/TLjx
                NciSxVwWulJNuBDxuk+tAKS33wrAeuYscrxOiK86eNw8S2qPcMnGBD1v1QsSDf5SgCY5gF
                uj4GuRmie9zPInRtXlvFkKgEfEHGboohjGgX3eMdLknUhK4QEtBtkAIlG7yFS52X8Kvv1+
                y9BigF2YdmYNbiLQoCH95h1A/2968T2OkkM/GQRCI+DG/7tzI8ysIfU7XsAYJDkoRRHH5k
                b3NSK5gKr4E0EVg+Pj7SShHmMR9jLVht/OKdWnP0kBlV/Byt+wh23bmZ/QL3MK627ZIM1S
                HHpmg7Woh/n0hyXlOXsNdn39J5XM2FT5DOG8cgXeQ6aTYu+DuyxfXuYbTIWckKL3jRv7nY
                f4RacLLNyOoAxFhSIhb1tvQxIpn5yv8CL8d2D49Sf5FR6D8w
          passphrase: 60874022
          script: |
            sudo docker-compose stop
            sudo docker-compose rm web
            touch .env
            echo DB_ENGINE=${{ secrets.DB_ENGINE }} >> .env
            echo DB_NAME=${{ secrets.DB_NAME }} >> .env
            echo POSTGRES_USER=${{ secrets.POSTGRES_USER }} >> .env
            echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} >> .env
            echo DB_HOST=${{ secrets.DB_HOST }} >> .env
            echo DB_PORT=${{ secrets.DB_PORT }} >> .env
            sudo docker-compose up -d
  send_message:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
    - name: send message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: ${{ github.workflow }} успешно выполнен!
